apiVersion: v1
kind: Pod
metadata:
  name: hello.smarthitters.com 
  labels:
    app: docker-containers
spec:
  containers:
  - name: docker-containers
    image: muralikante/docker-node-demo-container 
    ports:
    - name: nodejs-port
      containerPort: 5000
