apiVersion: v1
kind: ReplicationController
metadata:
  name: hitters-controller
spec:
  replicas: 2
  selector:
    app: docker-containers
  template:
    metadata:
      labels:
        app: docker-containers
    spec:
      containers:
      - name: docker-container-node-demo
        image: muralikante/docker-node-demo-container
        ports:
        - name: nodejs-port
          containerPort: 5000
