apiVersion: v1
kind: ReplicationController
metadata:
  name: hitters-controller
spec:
  replicas: 2
  selector:
    app: docker-containers
  template:
    metadata:
      labels:
        app: docker-containers
    spec:
      containers:
      - name: docker-container-node-demoi-1
        image: muralikante/docker-node-demo-container
        ports:
        - name: nodejs-port
          containerPort: 5000
      - name: key-value-store
        image: redis
        ports:
         - containerPort: 6379
