apiVersion: v1
kind: Pod
metadata:
  name: hitters-nginx
  labels:
    app: hitters-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  - name: nodejs-demo 
    image: muralikante/docker-node-demo-container:5.0
    ports:
    - containerPort: 5000
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
        - key: reverseproxy.conf
          path: reverseproxy.conf
