apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hitters-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-containers
    spec:
      containers:
      - name: nodejs-demo
        image: muralikante/docker-node-demo-container
        ports:
        - name: nodejs-port
          containerPort: 5000
      - name: key-value-store
        image: redis
        ports:
         - containerPort: 6379