apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hitters-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hitters-app
    spec:
      containers:
      - name: docker-containers 
        image: muralikante/docker-node-demo-container
        command: ["node", "index-db.js"]
        ports:
        - name: nodejs-port
          containerPort: 3000
        env:
          - name: MYSQL_HOST
            value: database-service
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: helloworld-secrets
                key: rootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: helloworld-secrets
                key: database
