apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hitters-deployment-service-discovery
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hitters-app
    spec:
      containers:
      - name: docker-containers 
        image: muralikante/docker-node-demo-container:6.0
        command: ["node", "index-database.js"]
        ports:
        - name: nodejs-port
          containerPort: 3000
        env:
          - name: MYSQL_HOST
            value: database-service
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hitters-secrets
                key: rootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: hitters-secrets
                key: database
